### ISSUE TITLE
Add, edit, remove courses

### ISSUE THREAD

**Issue by huseinr2493** [uwstout-cs458-s22/advisor001-api#10]
As an advisor I want to add, edit, and remove courses so the database contains the latest information needed for the semester

**Comment by huseinr2493** [comment]
- An endpoint exists for creating courses
- An endpoint exists for updating courses
  - Suggested: `POST /course/<some id>` with JSON payload
- An endpoint exists for deleting courses
  - Suggested: `DELETE /course/<some id>` with JSON payload
- Valid mock tests are created for these endpoints
- This feature passes all mock tests

**Comment by bvoigt00** [comment]
We could split this user story into three user stories, one each for adding, editing, and removing courses.

**Comment by huseinr2493** [comment]
Update:

The frontend tries to use these endpoints but they don't exist yet.
- GET /users/add
- GET /users/edit/<id here>
- GET /users/delete/<id here>

For continuity purposes, I suggest we stick to this scheme and use
- GET /courses/add
- GET /courses/edit/<id here>
- GET /courses/delete/<id here>

**Comment by huseinr2493** [comment]
(Deleted a comment because the information was not correct)

**Comment by huseinr2493** [comment]
We now have #46 and #42
