### ISSUE TITLE
Edit Users Endpoint

### ISSUE THREAD

**Issue by joshua-elmer** [uwstout-cs458-s22/advisor001-api#15]
As an Advisor, I would like to be able to edit the information about a User (Such as their name, major, current/previous courses) and adjust the permissions attached to their account, so that if a student changes majors this can be done within the program.

- The program updates the user based on the information given, (email, name) and does so via JSON.
- Responds with a 404 response code when the student to be edited is not found
- Responds with a 200 response code when the student record exists and is edited.
- Responds with a 400 when queried with missing or malformed parameters.
- Responds with a 500 whenever any other detectable error condition is triggered

**Comment by huseinr2493** [comment]
When we get these user endpoints going, we should tell the frontend team how those endpoints work.

**Comment by ErikDrake27** [comment]
Will communicate with the front-end team as to what they are expecting to be editable.

**Comment by huseinr2493** [comment]
**Addendum**
* The endpoint shall return 401 if whoever is trying to edit doesn't have permission

**Comment by huseinr2493** [comment]
It is necessary to communicate the return value of `authenticateStytchSession` because the endpoint needs to know whether we have permission to do this edit or not.
