### ISSUE TITLE
User route ends in "s" but the rest don't

### ISSUE THREAD

**Issue by huseinr2493** [uwstout-cs458-s22/advisor001-api#90]
I have noticed that the user route is `/users/<id>` while the rest are non-plural, like `/course/<id>`. Also the thing about `/users/` taking in the stytch ID to edit and delete, instead of the serial ID. Would these be things we want to change, or would it just further complicate matters with the frontend team?

**Comment by joshua-elmer** [comment]
I'll take note of this and ask frontend for their input on Friday during Scrum of Scrums! Or feel free to reach out and ask them through the Teams chat we made last week

**Comment by joshua-elmer** [comment]
Spoke with front end and determined that a change at this point would be detrimental to existing functionality.
